# Start with official image Pythona 3.9 (python:3.9-slim-buster)

# Set the working directory in the container to /app

# Copy app.py templates/index.html requirements.txt into the container at /app

# Install any dependencies in requirements.txt (pip)

# Expose port 8000 for the application to listen on

# Set the command to run the application
