version: '3'
services:
  api:
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - default
  web:
    build:
      context: web
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - default